sudo: true
os: linux
dist: trusty
language: golang
env:
        GOPATH=$PWD
notifications:
email:
        on_success: never
        on_failure: never
script:
- cd src/mapreduce
- go test -run Sequential
- go test -run TestParallel
